=== RudzinskyiYurii/EpamLessons/main/resources/xml/devicesXSD.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" >

    <xsd:element name = 'devices'>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name = 'device' type = 'deviceType' minOccurs = '0'
                            maxOccurs = 'unbounded' />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name = "deviceType">
        <xsd:sequence>
            <xsd:element name = "name" type = "xsd:string"/>
            <xsd:element name = "origin" type = "xsd:string"/>
            <xsd:element name="price">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="types">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="peripheral" type="xsd:string"/>
                        <xsd:element name="cooler" type="xsd:string"/>
                        <xsd:element name="powerWAT">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:integer">
                                    <xsd:minInclusive value="0"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>
                        <xsd:element name="accessoriesGroup">
                            <xsd:complexType>
                                <xsd:choice maxOccurs="unbounded">
                                    <xsd:element name="accessory" type="xsd:string"/>
                                </xsd:choice>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="ports">
                            <xsd:complexType>
                                <xsd:choice maxOccurs="unbounded">
                                    <xsd:element name="port" type="xsd:string"/>
                                </xsd:choice>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name = "critical" type = "xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name = 'devNO' type = 'xsd:integer'/>
    </xsd:complexType>
</xsd:schema>

=== RudzinskyiYurii/EpamLessons/main/resources/xml/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
 <?xml-stylesheet type="text/xsl" href="devicesXSL.xsl"?>

<devices
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="devicesXSD.xsd">

    <device devNO="0">
        <name>IBM</name>
        <origin>UK</origin>
        <price>40000</price>
        <types>
            <peripheral>yes</peripheral>
            <cooler>yes</cooler>
            <powerWAT>1000</powerWAT>
            <accessoriesGroup>
                <accessory>multimedia</accessory>
                <accessory>inputOutput</accessory>
            </accessoriesGroup>
            <ports>
                <port>COM</port>
                <port>LPT</port>
            </ports>
        </types>
        <critical>no</critical>
    </device>

    <device devNO="1">
        <name>MultimediaPC</name>
        <origin>USA</origin>
        <price>30000</price>
        <types>
            <peripheral>yes</peripheral>
            <cooler>yes</cooler>
            <powerWAT>900</powerWAT>
            <accessoriesGroup>
                <accessory>multimedia</accessory>
            </accessoriesGroup>
            <ports>
                <port>COM</port>
                <port>USB</port>
            </ports>
        </types>
        <critical>yes</critical>
    </device>

    <device devNO="2">
        <name>ZenBook</name>
        <origin>France</origin>
        <price>50000</price>
        <types>
            <peripheral>yes</peripheral>
            <cooler>yes</cooler>
            <powerWAT>800</powerWAT>
            <accessoriesGroup>
                <accessory>multimedia</accessory>
                <accessory>inputOutput</accessory>
            </accessoriesGroup>
            <ports>
                <port>USB</port>
                <port>LPT</port>
            </ports>
        </types>
        <critical>no</critical>
    </device>

</devices>
